/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BusinessAbility: typeof import('./src/components/llm-gen/BusinessAbility/index.vue')['default']
    DropdownArrow: typeof import('./src/components/icons/DropdownArrow.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FinancialMineChart: typeof import('./src/components/llm-gen/FinancialMineChart/index.vue')['default']
    GenModule: typeof import('./src/components/llm-gen/GenModule/index.vue')['default']
    Holder: typeof import('./src/components/llm-gen/Holder/index.vue')['default']
    MainBusiness: typeof import('./src/components/llm-gen/MainBusiness/index.vue')['default']
    MainBussiness: typeof import('./src/components/llm-gen/MainBussiness/index.vue')['default']
    Reset: typeof import('./src/components/icons/Reset.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowDetails: typeof import('./src/components/icons/showDetails.vue')['default']
    ZoomIn: typeof import('./src/components/icons/zoomIn.vue')['default']
    ZoomOut: typeof import('./src/components/icons/zoomOut.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
